# Generated by Django 4.2.3 on 2023-08-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisment', '0003_advetisment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='advetisment',
            name='image',
            field=models.ImageField(default='', upload_to='advertisement/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
