# Generated by Django 4.2.3 on 2023-08-02 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_lesson_4', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advetisment',
        ),
    ]
